-- Generated by scripts/atlas-import.mjs
-- Created at 2026-04-06T12:14:32.923Z

insert into public.plants (name, description, image_url, latitude, longitude, tags, status, created_by)
select '山茶', '冬末到早春最有存在感的园林花木之一，花色饱满，叶面油亮。', '/plants/atlas/camellia.jpg', 30.2741, 120.1551, ARRAY['冬季', '华东', '观花', '庭院', '常绿']::text[], 'approved', null
where not exists (
  select 1 from public.plants
  where lower(name) = lower('山茶')
    and abs(latitude - 30.2741) < 0.00001
    and abs(longitude - 120.1551) < 0.00001
);

insert into public.plants (name, description, image_url, latitude, longitude, tags, status, created_by)
select '银杏', '金黄色叶片在秋季最动人，是许多城市街道最具辨识度的树种之一。', '/plants/atlas/ginkgo.JPG', 37.5665, 126.978, ARRAY['秋季', '东亚', '秋色', '乔木', '城市']::text[], 'approved', null
where not exists (
  select 1 from public.plants
  where lower(name) = lower('银杏')
    and abs(latitude - 37.5665) < 0.00001
    and abs(longitude - 126.978) < 0.00001
);

insert into public.plants (name, description, image_url, latitude, longitude, tags, status, created_by)
select '荷花', '挺水而生，花与叶层层展开，是东方园林里最经典的夏日景致。', '/plants/atlas/lotus.jpg', 31.2989, 120.5853, ARRAY['夏季', '江南', '水生', '观花', '池塘']::text[], 'approved', null
where not exists (
  select 1 from public.plants
  where lower(name) = lower('荷花')
    and abs(latitude - 31.2989) < 0.00001
    and abs(longitude - 120.5853) < 0.00001
);

insert into public.plants (name, description, image_url, latitude, longitude, tags, status, created_by)
select '樱花', '花期虽短，却总能把一个城市的春天定格成共同记忆。', '/plants/atlas/sakura.jpg', 35.6762, 139.6503, ARRAY['春季', '东亚', '观花', '城市', '温带']::text[], 'approved', null
where not exists (
  select 1 from public.plants
  where lower(name) = lower('樱花')
    and abs(latitude - 35.6762) < 0.00001
    and abs(longitude - 139.6503) < 0.00001
);

insert into public.plants (name, description, image_url, latitude, longitude, tags, status, created_by)
select '蓝花楹', '蓝紫色花冠在街道上像一片轻盈云雾，是春末最有记忆点的城市树景。', '/plants/atlas/jacaranda.jpg', -34.6037, -58.3816, ARRAY['春季', '南美', '观花', '乔木', '城市']::text[], 'approved', null
where not exists (
  select 1 from public.plants
  where lower(name) = lower('蓝花楹')
    and abs(latitude - -34.6037) < 0.00001
    and abs(longitude - -58.3816) < 0.00001
);

insert into public.plants (name, description, image_url, latitude, longitude, tags, status, created_by)
select '郁金香', '颜色整齐、花型干净，是最能代表春天秩序感的花卉之一。', '/plants/atlas/tulip.JPG', 52.3676, 4.9041, ARRAY['春季', '欧洲', '观花', '花田', '球根']::text[], 'approved', null
where not exists (
  select 1 from public.plants
  where lower(name) = lower('郁金香')
    and abs(latitude - 52.3676) < 0.00001
    and abs(longitude - 4.9041) < 0.00001
);

insert into public.plants (name, description, image_url, latitude, longitude, tags, status, created_by)
select '桃花', '柔软的粉色花云沿着山谷铺开，是高原春季最有节庆感的景致之一。', '/plants/atlas/peachblossom.jpg', 29.6548, 94.3499, ARRAY['春季', '东亚', '观花', '山谷', '春景']::text[], 'approved', null
where not exists (
  select 1 from public.plants
  where lower(name) = lower('桃花')
    and abs(latitude - 29.6548) < 0.00001
    and abs(longitude - 94.3499) < 0.00001
);

insert into public.plants (name, description, image_url, latitude, longitude, tags, status, created_by)
select '紫藤', '瀑布状花串垂下时，能让廊架和老院子瞬间拥有戏剧性的浪漫。', '/plants/atlas/wisteria.jpg', 34.6937, 135.5023, ARRAY['春季', '东亚', '藤本', '观花', '庭院']::text[], 'approved', null
where not exists (
  select 1 from public.plants
  where lower(name) = lower('紫藤')
    and abs(latitude - 34.6937) < 0.00001
    and abs(longitude - 135.5023) < 0.00001
);

insert into public.plants (name, description, image_url, latitude, longitude, tags, status, created_by)
select '向日葵', '大片花盘随日照转动，常被用来记录田野与公路旅途的明亮瞬间。', '/plants/atlas/sunflower.jpg', 38.5, -98, ARRAY['夏季', '北美', '花田', '观花', '高辨识度']::text[], 'approved', null
where not exists (
  select 1 from public.plants
  where lower(name) = lower('向日葵')
    and abs(latitude - 38.5) < 0.00001
    and abs(longitude - -98) < 0.00001
);

insert into public.plants (name, description, image_url, latitude, longitude, tags, status, created_by)
select '薄衣草', '整片花田在风里起伏，带着清新的草本香气，是最适合夏季远行的植物景观。', '/plants/atlas/lavender.jpg', 43.834, 5.792, ARRAY['夏季', '欧洲', '芳香', '观花', '花田']::text[], 'approved', null
where not exists (
  select 1 from public.plants
  where lower(name) = lower('薄衣草')
    and abs(latitude - 43.834) < 0.00001
    and abs(longitude - 5.792) < 0.00001
);

insert into public.plants (name, description, image_url, latitude, longitude, tags, status, created_by)
select '茫莉', '花朵洁白，香气柔和，在南方城市和院落里都很常见。', '/plants/atlas/jasmine.jpg', 21.0278, 105.8342, ARRAY['夏季', '东南亚', '芳香', '观花', '庭院']::text[], 'approved', null
where not exists (
  select 1 from public.plants
  where lower(name) = lower('茫莉')
    and abs(latitude - 21.0278) < 0.00001
    and abs(longitude - 105.8342) < 0.00001
);

insert into public.plants (name, description, image_url, latitude, longitude, tags, status, created_by)
select '三角梅', '枝条舒展、色彩明亮，常把街角和屋顶边缘点缀得非常热烈。', '/plants/atlas/bougainvillea.jpg', -22.9068, -43.1729, ARRAY['夏季', '南美', '热带', '观花', '街景']::text[], 'approved', null
where not exists (
  select 1 from public.plants
  where lower(name) = lower('三角梅')
    and abs(latitude - -22.9068) < 0.00001
    and abs(longitude - -43.1729) < 0.00001
);
